resources:
  - repo: self
queue:
  name: Hosted macOS
  demands:
    - xcode
    - sh

steps:
  - task: InstallAppleCertificate@2
    displayName: 'Install an Apple certificate'
    inputs:
      certSecureFile: 'mac_distribution_signing_key.p12'
      certPwd: '$(mac_distribution_signing_password)'

  - task: Xcode@5
    displayName: 'Build DEP Notify'
    inputs:
      xcodeVersion: '10'
      actions: 'build'
      xcWorkspacePath: 'DEPNotify.xcodeproj'
      sdk: 'macosx10.14'
      args: '-target DEPNotify'
   

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'DEPNotify.app'
      targetPath: 'build/Release/DEPNotify.app'

