resources:
  - repo: self
queue:
  name: Hosted macOS
  demands:
    - xcode
    - sh

steps:
  - task: InstallAppleCertificate@2
    displayName: 'Install an Apple certificate'
    inputs:
      certSecureFile: 'mac_distribution_signing_key.p12'
      certPwd: '$(mac_distribution_signing_password)'

  - task: Xcode@5
    displayName: 'Build DEP Notify'
    inputs:
      xcodeVersion: '10'
      actions: 'build'
      xcWorkspacePath: 'DEPNotify.xcodeproj'
      sdk: 'macosx10.14'
      args: '-target DEPNotify'
    disabled: true
   
  - task: Xcode@5
    inputs:
      actions: 'build'
      packageApp: false
      signingOption: 'default'
      destinationPlatformOption: 'macOS'
      args: '-target DEPNotify'

  
  - task: PublishPipelineArtifact@0
    displayName: 'Publish DEP_NOTIFY_APP'
    inputs:
      artifactName: DEP_NOTIFY_APP
      targetPath: '$(Agent.BuildDirectory)/s/build'
