resources:
  - repo: self
queue:
  name: Hosted macOS
  demands:
    - xcode
    - sh

steps:
  - task: InstallAppleCertificate@2
    displayName: 'Install an Apple certificate'
    inputs:
      certSecureFile: 'mac_distribution_signing_key.p12'
      certPwd: '$(mac_distribution_signing_password)'

- task: InstallAppleCertificate@2
  displayName: 'Install a second test Apple certificate'
  inputs:
    certSecureFile: '$(Test_Certificate)'
    certPwd: '$(test_cert_password)'

  - task: Xcode@5
    displayName: 'Build DEP Notify'
    inputs:
      xcodeVersion: '10'
      xcWorkspacePath: 'DEPNotify.xcodeproj'
      actions: 'build'
      signingOption: auto
      sdk: 'macosx10.14'
      args: '-target DEPNotify'


  - task: CmdLine@2
    displayName: 'create an archive'
    inputs:
      script: |
        cd $(Agent.BuildDirectory)/s/build/
        zip -r DEPNotify.zip Release/

    
  - task: PublishPipelineArtifact@0
    displayName: 'Publish DEP_NOTIFY_APP'
    inputs:
      artifactName: DEP_NOTIFY_APP
      targetPath: '$(Agent.BuildDirectory)/s/build/DEPNotify.zip'
