resources:
  - repo: self
queue:
  name: Hosted macOS
  demands:
    - xcode
    - sh

steps:
  - task: InstallAppleCertificate@2
    displayName: 'Install an Apple certificate'
    inputs:
      certSecureFile: 'mac_distribution_signing_key.p12'
      certPwd: '$(mac_distribution_signing_password)'

  - task: Xcode@5
    displayName: 'Build DEP Notify'
    inputs:
      xcodeVersion: '10'
      xcWorkspacePath: 'DEPNotify.xcodeproj'
      actions: 'build'
      sdk: 'macosx10.14'
      args: '-target DEPNotify'

  - task: CmdLine@2
    displayName: 'create an archive'
    inputs:
      script: |
        zip -r $(Agent.BuildDirectory)/s/DEPNotify.zip $(Agent.BuildDirectory)/s/build/Release/

    
  - task: PublishPipelineArtifact@0
    displayName: 'Publish DEP_NOTIFY_APP'
    inputs:
      artifactName: DEP_NOTIFY_APP
      targetPath: '$(Agent.BuildDirectory)/s/DEPNotify.zip'
