resources:
  - repo: self
pool:
  name: Azure Pipelines
  vmImage: macos-11

steps:
  - task: InstallAppleCertificate@2
    displayName: 'Install an Apple application signing certificate'
    inputs:
      certSecureFile: '$(Application_signing_certificate)'
      certPwd: '$(Application_signing_certificate_password)'
      

  - task: CmdLine@2
    displayName: Check for signing identities
    inputs:
      script: 'security find-identity -v -p codesigning'
    
      
  - task: Xcode@5
    displayName: 'Build DEP Notify'
    inputs:
      xcodeVersion: 'specifyPath'
      xcodeDeveloperDir: '/Applications/Xcode_12.4.app'
      xcWorkspacePath: 'DEPNotify.xcodeproj'
      actions: 'build'
      signingOption: 'manual'
      signingIdentity: 'Developer ID Application: ThoughtWorks Deutschland GmbH (V25DK7S622)'
      sdk: 'macOS 11.1'
      args: '-target DEPNotify OTHER_CODE_SIGN_FLAGS="--timestamp" CODE_SIGN_INJECT_BASE_ENTITLEMENTS="NO"'
  
  - task: CmdLine@2
    displayName: 'create an archive of DEPNotify.app'
    inputs:
      script: |
        cd $(Agent.BuildDirectory)/s/build/
        zip -r DEPNotify.zip Release/

    
  - task: PublishPipelineArtifact@0
    displayName: 'Publish DEP_NOTIFY_APP'
    inputs:
      artifactName: DEP_NOTIFY_APP
      targetPath: '$(Agent.BuildDirectory)/s/build/DEPNotify.zip'
