resources:
  - repo: self
queue:
  name: Hosted macOS
  demands:
    - xcode
    - sh

steps:
  - task: InstallAppleCertificate@2
    displayName: 'Install an Apple certificate'
    inputs:
      certSecureFile: 'mac_distribution_signing_key.p12'
      certPwd: '$(mac_distribution_signing_password)'

  - task: Xcode@5
    displayName: 'Build DEP Notify'
    inputs:
      xcodeVersion: '10'
      actions: 'build'
      xcWorkspacePath: 'DEPNotify.xcodeproj'
      sdk: 'macosx10.14'
      args: '-target DEPNotify'
   

  - task: CopyFiles@2
    displayName: 'Copy built app to staging directory'
    inputs:
      contents: '**/DEPNotify.app'
      targetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishPipelineArtifact@0
    displayName: 'Publish DEP Notify package'
    inputs:
      artifactName: DEPNotifyPackage
      targetPath: '$(build.artifactStagingDirectory)/DEPNotify.app'

